---
title: "supplemental_figures_8.20.Rmd"
author: "Scott Klasek"
date: "8/31/2020"
output: github_document
---

## load necessary libraries and data
```{r}
library(phyloseq)
library(tidyverse)
library(patchwork)
library(tables)
library(here)
sessioninfo <- sessionInfo()
ps.frdp <- readRDS(file="ps.frdp") # imports the final phyloseq object
```

## depth-integrated fluxes from each core
PC1029 is only estimated, others can be calculated
```{r}
aomrates <- read.csv(file="~/Desktop/svalflux/aomrates2020update.csv") # import csv

cores <- as.factor(as.character(levels(aomrates$core)[2:8])) # get a list of the cores
maxdepth <- vector("numeric", length(cores)) # define a vector for writing max depths
for (i in cores) {maxdepth[[i]] <- max((aomrates %>% filter(core==i))$depth)} # for-loop to calculate max depth
maxdepth <- maxdepth[(0.5*length(maxdepth)+1):length(maxdepth)] # omitted zero values
intflux <- vector("numeric", length(cores)) # define a vector for calculating fluxes
for (i in cores) {intflux[[i]] <- sum((aomrates %>% filter(core==i))$aom)*(1e4 * 365 / 1e9)} # for-loop to calculate flux (converting micromoles per L per day to moles per m^2 per year)
intflux <- intflux[(0.5*length(intflux)+1):length(intflux)] # omitted zero values

fluxes <- as.data.frame(cbind(maxdepth, intflux)) # combine into data frame
fluxes$core <- rownames(fluxes) # add core names
flux.gc <- fluxes[1:6,] # subset only the gravity cores (not as confident about the rates for PC1029)
flux.gc$stage <- c("increasing methane flux", "steady-state", "steady-state", "steady-state", "steady-state", "increasing methane flux") # add stage

gcf <- ggplot(flux.gc,aes(core,intflux,fill=stage))
gg.flux <- gcf+geom_bar(stat="identity")+
  scale_fill_manual("Methane stage", values = c("#66c2a5", "#8da0cb"))+
  scale_y_continuous()+
  xlab("")+
  ylab(bquote(~CH[4]~'flux (mols'~m^-2~yr^-1*') at time of sampling'))+
  theme_classic()+
  theme(axis.text.y = element_text(size = 10),axis.text.x=element_text(angle = 45, hjust = 1,size=12))
flux.gc
gg.flux
gg.flux <- saveRDS(gg.flux, "figures/figureS1flux") # export figure
```

## regression of mcrA counts vs modeled AOM rates
```{r}
mcra.aom <- read.csv(file="~/Desktop/svalflux/mcra.aomrate.2020.csv") # import csv
mcra.aom$logaom <- log10(mcra.aom$aom) # calculate log of AOM rate
mcra.aom$logmcra <- log10(mcra.aom$mcra) # calculate log of mcrA gene abundance
mcra.aom$logdsrab <- log10(mcra.aom$dsrab) # calculate log of dsrAB gene abundance

mcra.aom$stage <- "steady-state"
mcra.aom[which(mcra.aom$core=="GC1045"),11] <- "increasing methane flux"
mcra.aom[which(mcra.aom$core=="GC1081"),11] <- "increasing methane flux"

AOM_mcrA.lm <- lm(mcra.aom$logmcra ~ mcra.aom$logaom) # linear raegression
summary(AOM_mcrA.lm) # multiple R^2 is 0.3364, slope estimate is 0.1892, and slope p-value is 0.00021 ***

rate_mcrA <- ggplot(mcra.aom,aes(logaom,logmcra,color=stage)) 
gg.ratemcrA <- rate_mcrA+
  geom_point(size=2)+
  scale_color_manual("Methane stage", values = c("#66c2a5", "#8da0cb"))+
  scale_x_continuous(expression('log'[10]*" AOM rate (µmols L"^{-1}*" day"^{-1}*")"))+
  scale_y_continuous(expression('log'[10]*' mcrA gene copies g'^{"-1"}))+
  geom_abline(intercept = 5.3889, slope = 0.18917)+
  theme(axis.title=element_text(size = 12), axis.text = element_text(size = 11), legend.title = element_text(size = 12), legend.text = element_text(size = 10))+
  annotate("text", x = -4.5, y = 7.5, label = "paste(italic(R) ^ 2, \" = 0.3364\")", parse = TRUE)+
  annotate("text", x = -4.5, y = 7.2, label = "paste(italic(p), \" = 0.00021\")", parse = TRUE)+
  annotate("text", x = -4.5, y = 6.9, label = "paste(slope, \" = 0.1892\")", parse = TRUE)+
  annotate("rect", xmin = -6, xmax = -3, ymin = 6.6, ymax = 7.8, alpha = .2)+
  theme_bw()
gg.ratemcrA 
gg.ratemcrA <- saveRDS(gg.ratemcrA, "figures/figureS3ratemcrAplot") # export figure
```

## justification of steady-state dynamics
```{r}
ssval <- read.csv(file="~/Desktop/svalflux/steadystate_validation.csv") # import csv
ssval <- ssval[,1:4] # trim the columns with no data
ssjp <- ggplot(ssval,aes(depth,value,color=type))
ssjp.plot <- ssjp+
  geom_point(data=subset(ssval, type=="empirical"))+
  geom_line()+
  coord_flip()+
  facet_grid(~core)+
  scale_y_continuous("Sulfate (mM)",limits = c(0,30),position = "right")+
  scale_color_manual("Sulfate profile data type:",values = c("dodgerblue1","black"))+
  scale_x_reverse("Depth (cmbsf)",breaks=c(0,50,100,150,200,250,300,350),limits=c(350,0))+
  theme_bw()+
  theme(legend.position = "bottom")
ssjp.plot
ssjp.plot <- saveRDS(ssjp.plot, "figures/figureS3ssjust") # export figure
```

## table of core info
```{r}
coreinfo <- read.csv(file="~/Desktop/svalflux/coreinfo.csv") # import csv
names(coreinfo)[1:6] <- c("Core", "Latitude", "Longitude", "Water depth (m)", "Core recovery (cm)", "SMT depth (cm)")
coreinfo
coreinfo <- saveRDS(coreinfo, "figures/coreinfo") # export
```

## table of flux histories 
```{r}
inc.core <- read.csv(file="~/Desktop/svalflux/increasing.core.flux.table.csv") # import csv
names(inc.core)[2:4] <- c("Year before sampling", "CH4 flux mols m^-2 yr ^-1", "Peak AOM depth (cm)") # rename columns to be more legible
inc.core
inc.core <- saveRDS(inc.core, "figures/inc.core") # export
```